theme = "base16_transparent"

[editor]
line-number = "relative"
bufferline = "multiple"

[editor.statusline]
left = ["mode", "separator", "file-name", "file-modification-indicator", "spinner"]
right = ["diagnostics", "spacer", "selections", "separator", "position", "separator", "position-percentage", "spacer", "file-encoding"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.soft-wrap]
enable = true
max-wrap = 20    # increase value to reduce forced mid-word wrapping
max-indent-retain = 40   # Maximum indentation to carry over when soft wrapping a line.
wrap-indicator = "  ↪"


#Uncomment if indentation guide is needed
#[editor.indent-guides]
#render = true
